#!/bin/bash

# FactoryFlow ERP - PostgreSQL Setup Script

echo "🚀 Setting up PostgreSQL for FactoryFlow ERP"
echo "=========================================="

echo "📋 Instructions for PostgreSQL setup:"
echo ""
echo "Option 1 - Neon (Recommended):"
echo "1. Go to https://neon.tech"
echo "2. Create free account"
echo "3. Create new project 'factoryflow-erp'"
echo "4. Copy connection string"
echo ""
echo "Option 2 - Supabase:"
echo "1. Go to https://supabase.com"
echo "2. Create free account"
echo "3. Create new project 'factoryflow-erp'"
echo "4. Go to Settings → Database"
echo "5. Copy connection string"
echo ""
echo "Option 3 - Railway:"
echo "1. Go to https://railway.app"
echo "2. Create free account"
echo "3. Deploy PostgreSQL service"
echo "4. Copy connection string"
echo ""

echo "⚙️ After getting your database URL:"
echo ""
echo "For Vercel deployment:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your project 'factoryflow-erp'"
echo "3. Go to Settings → Environment Variables"
echo "4. Add variable:"
echo "   Name: DATABASE_URL"
echo "   Value: your_postgresql_connection_string"
echo "   Environment: Production"
echo ""
echo "5. Add variable:"
echo "   Name: NEXT_PUBLIC_BASE_URL"
echo "   Value: https://your-app-name.vercel.app"
echo "   Environment: Production"
echo ""

echo "🔄 For local testing with PostgreSQL:"
echo "1. Create .env.local file"
echo "2. Add: DATABASE_URL=\"your_postgresql_connection_string\""
echo "3. Run: npm run db:migrate"
echo "4. Run: npm run db:seed"
echo ""

echo "✅ Ready to deploy!"
